/**:
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: false
    costmap_topic: /global_costmap/costmap
    costmap_updates_topic: /global_costmap/costmap_updates
    visualize: true
    planner_frequency: 0.00005
    progress_timeout: 40.0
    potential_scale: 0.01
    orientation_scale: 0.0
    gain_scale: 5.0
    transform_tolerance: 1.0
    min_frontier_size: 0.2